version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: daily
    open-pull-requests-limit: 0
    target-branch: 'next-release'
    commit-message:
      prefix: '[skip netlify]'
