name: 'Lint PR title'

on:
  pull_request:
    branches:
      - release
    types: [opened, edited, synchronize]

jobs:
  lint:
    name: Lint PR
    runs-on: ubuntu-latest
    if: "startsWith(github.base_ref, 'release')"
    steps:
      - uses: amannn/action-semantic-pull-request@v1.2.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
