name: 'Branch guard'

on:
  pull_request:
    types: [opened, edited, synchronize]

jobs:
  allowed-to-merge-to-master:
    name: Check if allowed to merge to master
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Allowed to merge to master
        if: "!(startsWith(github.head_ref, 'release'))"
        run: |
          echo "";
          echo "head branch is: $GITHUB_HEAD_REF"
          echo "*****";
          echo "::error::Only release branch is allowed to merge to master";
          exit 1;
