# if the base_ref(target branch we want to merge to) is master and the head_ref(source branch we want to merge from)
# Then throw an error, as only release is allowed to merge into master
# Otherwise this action won't run and show as success
name: 'Branch guard'

on:
  pull_request:

jobs:
  can-merge-to-branch:
    name: Can merge to branch
    if: "github.base_ref == 'master' && !(startsWith(github.head_ref, 'release'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Checking if branch is allowed...
        run: |
          echo "";
          echo "::error::Not allowed to merge '$GITHUB_HEAD_REF' branch into '$GITHUB_BASE_REF' branch";
          echo "---";
          exit 1;
