name: 'Branch guard'

on:
  pull_request:
    branches:
      - master
    types: [opened, edited, synchronize]

jobs:
  allowed-to-merge-to-master:
    name: Check if allowed to merge to master
    if: "!(startsWith(github.head_ref, 'master'))"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Allowed to merge to master
        run: echo "::error:: **Only release is allowed to merge to master**"; exit 1;
