name: reviewdog
on:
  pull_request:
    branches:
      - master

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: eslint
        uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.github_token }}
          reporter: github-pr-check
          eslint_flags: 'src/'

  pRStatusGiphy:
    name: PR Status Giphy
    runs-on: ubuntu-latest
    steps:
      - name: PR Status Giphy
        uses: jzweifel/pr-status-giphy-action@master
        env:
          GIPHY_API_KEY: ${{ secrets.GIPHY_API_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
